### Makefile -- Functional configuration parser

# Author: Michael Grünewald
# Date: Sat Dec 28 13:07:19 CET 2013

# Configuration (https://github.com/michipili/configuration)
# This file is part of Configuration
#
# Copyright © 2012–2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		configuration

SRCS+=			configuration_Parser.mll
SRCS+=			configuration_Map.ml

.include "ocaml.lib.mk"

### End of file `Makefile'
